#!/bin/sh
#
set -x
#
#Parameter:
. /usr/local/etc/config/vob.conf
#
#debug "called with $1 and $2."
UPDATE=`date -Iseconds`
TIME=`date +%T`
#
if [ "$1" = "true" ]
then
	info "Kellertuere offen."
	# true: tuere offen
   /usr/local/etc/config/addons/vob/notification $cellardoor_open &
else
	info "Kellertuere zu."
  /usr/local/etc/config/addons/vob/notification $cellardoor_closed &   
fi  
exit 0
#EOF
